Going back to basics

diff --git a/usr/bin/elasticsearch b/usr/bin/elasticsearch
--- a/usr/bin/elasticsearch
+++ b/usr/bin/elasticsearch
@@ -1,5 +1,9 @@
 #!/bin/sh
 
+# OPTIONS:
+#   -f: start in the foreground
+#   -p <filename>: log the pid to a file (useful to kill it later)
+
 # CONTROLLING STARTUP:
 #
 # This script relies on few environment variables to determine startup
@@ -42,20 +46,6 @@
 # Be aware that you will be entirely responsible for populating the needed
 # environment variables.
 
-# Maven will replace the project.name with elasticsearch below. If that
-# hasn't been done, we assume that this is not a packaged version and the
-# user has forgotten to run Maven to create a package.
-
-IS_PACKAGED_VERSION='distributions'
-if [ "$IS_PACKAGED_VERSION" != "distributions" ]; then
-    cat >&2 << EOF
-Error: You must build the project with Maven or download a pre-built package
-before you can run Elasticsearch. See 'Building from Source' in README.textile
-or visit https://www.elastic.co/download to get a pre-built package.
-EOF
-    exit 1
-fi
-
 CDPATH=""
 SCRIPT="$0"
 
@@ -85,7 +75,6 @@ if [ "x$ES_INCLUDE" = "x" ]; then
                    /usr/local/share/elasticsearch/elasticsearch.in.sh \
                    /opt/elasticsearch/elasticsearch.in.sh \
                    ~/.elasticsearch.in.sh \
-                   "$ES_HOME/bin/elasticsearch.in.sh" \
                    "`dirname "$0"`"/elasticsearch.in.sh; do
         if [ -r "$include" ]; then
             . "$include"
@@ -100,7 +89,7 @@ fi
 if [ -x "$JAVA_HOME/bin/java" ]; then
     JAVA="$JAVA_HOME/bin/java"
 else
-    JAVA=`which java`
+    JAVA=$(which java)
 fi
 
 if [ ! -x "$JAVA" ]; then
@@ -113,14 +102,6 @@ if [ -z "$ES_CLASSPATH" ]; then
     exit 1
 fi
 
-# don't let JAVA_TOOL_OPTIONS slip in (e.g. crazy agents in ubuntu)
-# works around https://bugs.launchpad.net/ubuntu/+source/jayatana/+bug/1441487
-if [ "x$JAVA_TOOL_OPTIONS" != "x" ]; then
-    echo "Warning: Ignoring JAVA_TOOL_OPTIONS=$JAVA_TOOL_OPTIONS"
-    echo "Please pass JVM parameters via JAVA_OPTS instead"
-    unset JAVA_TOOL_OPTIONS
-fi
-
 # Special-case path variables.
 case `uname` in
     CYGWIN*)
@@ -129,29 +110,81 @@ case `uname` in
     ;;
 esac
 
-# full hostname passed through cut for portability on systems that do not support hostname -s
-# export on separate line for shells that do not support combining definition and export
-HOSTNAME=`hostname | cut -d. -f1`
-export HOSTNAME
+launch_service()
+{
+    pidpath=$1
+    foreground=$2
+    props=$3
+    es_parms="-Delasticsearch"
 
-# manual parsing to find out, if process should be detached
-daemonized=`echo $* | egrep -- '(^-d |-d$| -d |--daemonize$|--daemonize )'`
-if [ -z "$daemonized" ] ; then
-    exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" \
-          org.elasticsearch.bootstrap.Elasticsearch start "$@"
-else
-    exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" \
-          org.elasticsearch.bootstrap.Elasticsearch start "$@" <&- &
-    retval=$?
-    pid=$!
-    [ $retval -eq 0 ] || exit $retval
-    if [ ! -z "$ES_STARTUP_SLEEP_TIME" ]; then
-      sleep $ES_STARTUP_SLEEP_TIME
+    es_parms="$es_parms -Des.path.conf=$OPENSHIFT_ELASTICSEARCH_DIR/conf"
+
+    if [ "x$pidpath" != "x" ]; then
+        es_parms="$es_parms -Des.pidfile=$pidpath"
     fi
-    if ! ps -p $pid > /dev/null ; then
-      exit 1
+
+    if [ "${ELASTICSEARCH_VERSION%%.*}" == '1' ]; then
+        class_name=org.elasticsearch.bootstrap.Elasticsearch
+    else
+        class_name=org.elasticsearch.bootstrap.ElasticSearch
     fi
-    exit 0
-fi
+
+    # The es-foreground option will tell ElasticSearch not to close stdout/stderr, but it's up to us not to background.
+    if [ "x$foreground" != "x" ]; then
+        es_parms="$es_parms -Des.foreground=yes"
+        exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS $es_parms -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" $props $class_name
+        # exec without running it in the background, makes it replace this shell, we'll never get here...
+        # no need to return something
+    else
+        # Startup ElasticSearch, background it, and write the pid.
+        exec "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS $es_parms -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" $props $class_name <&- &
+        return $?
+    fi
+}
+
+# Parse any command line options.
+args=`getopt vfhp:D:X: "$@"`
+eval set -- "$args"
+
+while true; do
+    case $1 in
+        -v)
+            "$JAVA" $JAVA_OPTS $ES_JAVA_OPTS $es_parms -Des.path.home="$ES_HOME" -cp "$ES_CLASSPATH" $props \
+                    org.elasticsearch.Version
+            exit 0
+        ;;
+        -p)
+            pidfile="$2"
+            shift 2
+        ;;
+        -f)
+            foreground="yes"
+            shift
+        ;;
+        -h)
+            echo "Usage: $0 [-f] [-h] [-p pidfile]"
+            exit 0
+        ;;
+        -D)
+            properties="$properties -D$2"
+            shift 2
+        ;;
+        -X)
+            properties="$properties -X$2"
+            shift 2
+        ;;
+        --)
+            shift
+            break
+        ;;
+        *)
+            echo "Error parsing argument $1!" >&2
+            exit 1
+        ;;
+    esac
+done
+
+# Start up the service
+launch_service "$pidfile" "$foreground" "$properties"
 
 exit $?
